# This is a Maven generic template with %Parameters% to be replaced befored it consumed
image: adoptopenjdk/maven-openjdk11

stages:     #List of stages for jobs, and their order of execution
  - build
  - docker-build
  - test
  - release
  - report

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  #TODO configure gitlab runner 'config.toml'  for tls docker-in-docker
  #see info https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  #see info https://docs.gitlab.com/runner/configuration/advanced-configuration.html
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
%PARAMS%
  
build app:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building application %APP_NAME%..."
    - mvn -B -U clean install -DskipTests=true
  artifacts:
    expire_in: 3 days
    paths:
      - ./target
  tags:
    - ci


docker build:
  stage: docker-build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - echo "updating docker registry..."
    - ls
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE 
  tags:
    - ci


unit tests:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... "
    - mvn -B test -DskipTests=false
  artifacts:
    when: always
    expire_in: 3 days
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - ci

release app:      
  stage: release  
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - echo "releasing latest %APP_NAME% in docker registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - %RELEASE_ONLY%
  tags:
    - ci

reports:
  stage: report
  image: alpine
  script:
    - echo "Testsing and code inspection reportings"
  tags:
    - ci
